TARGET := iphone:clang:16.5:15.0
ARCHS = arm64 arm64e
THEOS_PACKAGE_SCHEME = rootless

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TikTokXPrefs
TikTokXPrefs_FILES = TTXRootListController.m
TikTokXPrefs_FRAMEWORKS = UIKit
TikTokXPrefs_PRIVATE_FRAMEWORKS = Preferences
TikTokXPrefs_INSTALL_PATH = /Library/PreferenceBundles
# Hien version trong Settings, lay tu file control
TTX_VERSION := $(shell grep -m1 '^Version:' ../control | cut -d' ' -f2 | tr -d '\r')
TikTokXPrefs_CFLAGS = -fobjc-arc -DTTX_VERSION='"$(TTX_VERSION)"'

include $(THEOS_MAKE_PATH)/bundle.mk
